# Generated by Django 2.2.4 on 2019-08-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='brand',
        ),
    ]
